#!/usr/bin/env python3

import fnmatch
import html
import json
import pathlib
import yaml
from collections import defaultdict

from jinja2 import Environment, FileSystemLoader

TEMPLATE = pathlib.Path(__file__).parent / "templates" / "algorithm_overview.md.jinja2"


def _matches_any(value, patterns):
    """Return True if value matches any of the glob patterns (case-sensitive)."""
    return any(fnmatch.fnmatchcase(value, p) for p in patterns)


def load_filter_config(config_path):
    """Load and return the exclude lists from a YAML filter config file."""
    if config_path is None:
        return {"packages": [], "libs": [], "properties": []}

    with open(config_path) as f:
        config = yaml.safe_load(f)

    exclude = config.get("filter", {}).get("exclude", {})
    return {
        "packages": exclude.get("packages", []),
        "libs": exclude.get("libs", []),
        "properties": exclude.get("properties", []),
    }


def is_algorithm_excluded(cfg, exclude):
    """Return True if the algorithm should be excluded based on package or lib."""
    return _matches_any(cfg["package"], exclude["packages"]) or _matches_any(
        cfg["lib"], exclude["libs"]
    )


def filter_properties(properties, exclude):
    """Remove properties whose names match any pattern in exclude['properties']."""
    if not exclude["properties"]:
        return properties
    return {
        k: v
        for k, v in properties.items()
        if not _matches_any(k, exclude["properties"])
    }


def load_algorithms(input_path):
    with open(input_path) as f:
        return json.load(f)


def _load_repo_map(input_paths):
    """Load the map of packages -> repository generated by

    gh search repos --owner=<org> --archived=false --visibility=true --json=name,url

    This function takes several of the output jsons and loads all of them into a
    map such that the repository can be looked up from the package name
    """
    pkg_repos = {}
    for inp in input_paths:
        with open(inp, "r") as f:
            data = json.load(f)
            for repo in data:
                pkg_repos[repo["name"].lower()] = (repo["name"], repo["url"])

    return pkg_repos


def get_package_repo(pkg_name, pkg_repo_map):
    """Get the repository that belongs to this package"""
    return pkg_repo_map.get(pkg_name.lower(), (pkg_name, ""))


def apply_filters(algorithms, filter_config):
    result = {}
    for name, info in algorithms.items():
        if is_algorithm_excluded(info, filter_config):
            continue
        result[name] = {
            **info,
            "properties": filter_properties(info["properties"], filter_config),
        }
    return result


def group_by_package(algorithms, pkg_repo_map):
    groups = defaultdict(lambda: {"url": "", "packages": []})
    for name, info in algorithms.items():
        pkg_name, url = get_package_repo(info["package"], pkg_repo_map)
        groups[pkg_name]["url"] = url
        groups[pkg_name]["packages"].append(
            {
                "name": name,
                "lib": info["lib"],
                "description": info.get("description", ""),
                "properties": info["properties"],
            }
        )
    for pkg in groups:
        groups[pkg]["packages"].sort(key=lambda a: a["name"])
    return dict(sorted(groups.items(), key=lambda item: (item[0] == "", item[0])))


def _render_prop_value(value):
    """Render a property value as an HTML snippet (returned unescaped)."""
    if value is None:
        return "<em>none</em>"
    if isinstance(value, (list, dict)):
        return f"<code>{html.escape(json.dumps(value, ensure_ascii=False))}</code>"
    return f"<code>{html.escape(str(value))}</code>"


def render_page(template_path, packages, item_label, property_label):
    env = Environment(
        loader=FileSystemLoader(str(template_path.parent)),
        autoescape=False,
    )
    env.filters["render_prop_value"] = _render_prop_value
    total_algorithms = sum(len(group["packages"]) for group in packages.values())

    template = env.get_template(template_path.name)
    return template.render(
        packages=packages,
        total_algorithms=total_algorithms,
        total_packages=len(packages),
        item_label=item_label,
        property_label=property_label,
    )


def main(args):
    algorithms = load_algorithms(args.input)

    if args.filter_config:
        filter_config = load_filter_config(args.filter_config)
        algorithms = apply_filters(algorithms, filter_config)

    repo_map = _load_repo_map(args.repo_maps)

    packages = group_by_package(algorithms, repo_map)

    output = render_page(TEMPLATE, packages, args.item_label, args.property_label)

    with open(args.output, "w") as f:
        f.write(output)


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate an algorithm overview page from collected algorithm JSON data"
    )
    parser.add_argument(
        "--input",
        "-i",
        help="Input JSON file with algorithm information",
        type=pathlib.Path,
        required=True,
    )
    parser.add_argument(
        "--output",
        "-o",
        help="Output MyST markdown file path",
        type=pathlib.Path,
        required=True,
    )
    parser.add_argument(
        "--filter-config",
        help="Path to a YAML file with filter rules (packages, libs, properties to exclude)",
        type=pathlib.Path,
        default=None,
    )
    parser.add_argument(
        "--item-label",
        help="Singular label for each item, e.g. 'algorithm' or 'processor'",
        default="algorithm",
    )
    parser.add_argument(
        "--property-label",
        help="Singular label for each property, e.g. 'property' or 'parameter'",
        default="property",
    )
    parser.add_argument(
        "--repo-maps",
        help="Pass mappings of package names to github repositories",
        nargs="*",
        default=[],
    )

    args = parser.parse_args()
    main(args)
