name: Build preview
on:
  workflow_call:
    inputs:
      ref:
        description: The git ref for which the preview should be built
        type: string
        required: true
      linkcheck:
        description: Run the link-check and fail the workflow if it fails
        type: boolean
        required: false
        default: true
      upload-artifact:
        description: Upload an artifact for downstream consumption
        type: boolean
        required: false
        default: true
      pr-number:
        description: The PR number for identifying dependent PRs
        type: string
        required: false
      alg-info-artifact-id:
        description: The artifact ID to download for the algorithm overview
        required: false
        type: string
        default: ''
      proc-info-artifact-id:
        description: The artifact ID to download for the processor overview
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip
    - name: Install Requirements
      run: |
          pip install --upgrade pip
          pip install -r requirements.txt
    - name: Download algorithm overview
      if: ${{ inputs.alg-info-artifact-id != '' }}
      uses: actions/download-artifact@v5
      with:
        name: algorithm_overview-${{ inputs.ref }}
        path: artifact_download/
    - name: Move info
      if: ${{ inputs.alg-info-artifact-id != '' }}
      run: |
        mv artifact_download/algorithm-overview.md docs/
    - name: Download processor overview
      if: ${{ inputs.proc-info-artifact-id != '' }}
      uses: actions/download-artifact@v5
      with:
        name: processor_overview-${{ inputs.ref }}
        path: artifact_download/
    - name: Move processor info
      if: ${{ inputs.proc-info-artifact-id != '' }}
      run: |
        mv artifact_download/processor-overview.md docs/
    - name: Fetch external sources from upstream PR
      if: ${{ inputs.pr-number != '' }}
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        bash scripts/fetch_upstream_pr_sources.sh ${{ inputs.pr-number }}
    - name: Fetch external sources
      run: |
        bash scripts/fetch_external_sources.sh
    - name: Build documentation
      run: |
        sphinx-build -M html docs build
    - name: Run linkcheck
      if: ${{ inputs.linkcheck }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sphinx-build -b linkcheck docs linkcheck
    - uses: actions/upload-pages-artifact@v4
      if: ${{ inputs.upload-artifact }}
      with:
        path: build/html
