name: Generate processor overview
on:
  workflow_call:
    inputs:
      ref:
        description: The git ref for which the preview should be built
        type: string
        required: true
    outputs:
      artifact-id:
        description: The ID of the artifact with the generated markdown file
        value: ${{ jobs.generate-overview.outputs.artifact-id }}

jobs:
  generate-overview:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
      - uses: cvmfs-contrib/github-action-cvmfs@v5
      - uses: aidasoft/run-lcg-view@v5
        with:
          container: ubuntu2404
          view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
          run: |
            python3 scripts/collect_marlin_processor_info.py -o marlin_processors.json
            python3 scripts/generate_algorithm_page.py -i marlin_processors.json \
              -o processor-overview.md \
              --template scripts/templates/processor_overview.md.jinja2
      - uses: actions/upload-artifact@v6
        id: upload-artifact
        with:
          name: processor_overview-${{ inputs.ref }}
          path: processor-overview.md
