name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *' # end of every day

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref_name }}
      linkcheck: true

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        ref: gh-pages
    - uses: actions/download-artifact@v5
      with:
        name: github-pages
        path: doc_artifact
    - name: Update Documentation
      env:
        TARGET_DIR: ${{ github.ref_name }}
      run: |
        mkdir -p ${TARGET_DIR}
        rm -rf ${TARGET_DIR}/*
        tar -xvf doc_artifact/artifact.tar --directory ${TARGET_DIR}
        rm -r doc_artifact
    - name: Commit and Push changes
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: ${{ github.ref_name }}
      run: |
        git config --global user.email ${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com
        git config --global user.name ${GITHUB_ACTOR}
        git add ${TARGET_DIR}
        git diff-index --quiet HEAD 2>&1 > /dev/null || git commit -m "Update documentation for ${TARGET_DIR}" && git push
